services:
  db:
    image: postgres:17
    container_name: legal-matters-db
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_DATABASE}"]
      interval: 5s
      timeout: 5s
      retries: 5
      

  app:
    build: .
    container_name: legal-matters
    ports:
      - "8080:8080"
    environment:
      ConnectionStrings__Postgres: "Host=postgres;Port=5432;Database=taxcalculator;Username=postgres;Password=postgres"

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
    depends_on:
      migrate:
        condition: service_completed_successfully
        
  migrate:
    build: .
    container_name: migrate
    entrypoint: ["/app/efbundle"]
    environment:
      ConnectionStrings__Postgres: "Host=postgres;Port=5432;Database=taxcalculator;Username=postgres;Password=postgres"

    depends_on:
      db:
        condition: service_healthy

  e2e:
    profiles: ["e2e"]
    build:
      dockerfile: Dockerfile.playwright
      context: .
    container_name: e2e
    depends_on:
      app:
        condition: service_healthy
    environment:       
      CI: 1
    network_mode: "service:app"

volumes:
  postgres_data:
