services:
  db:

    image: postgres:17
    container_name: legal_matters_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file: .env.docker-compose
      
  app:
    build: .
    container_name: legal-matters
    ports:
      - "8080:8080"

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
    depends_on:
      migrate:
        condition: service_completed_successfully
    env_file: .env.docker-compose
        
  migrate:
    build: .
    container_name: legal-matters-migrate
    entrypoint: ["/app/efbundle"]
    depends_on:
      db:
        condition: service_healthy

    env_file: .env.docker-compose

volumes:
  postgres_data:
